// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uwl.Data.EntityFramework.Uwl_DbContext;

namespace UwlAPI.Tools.Migrations
{
    /// <summary>
    /// 
    /// </summary>
    [DbContext(typeof(UwlDbContext))]
    [Migration("20191004150118_20191004")]
    partial class _20191004
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.Logs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contents");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<string>("IPAddress");

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("NewXml");

                    b.Property<string>("OldXml");

                    b.Property<string>("Others");

                    b.Property<string>("Test");

                    b.Property<string>("Title");

                    b.Property<string>("TypeName");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysButton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("APIAddress");

                    b.Property<string>("ButtonStyle");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDrop");

                    b.Property<bool>("IsShow");

                    b.Property<string>("KeyCode");

                    b.Property<string>("Memo");

                    b.Property<Guid>("MenuId");

                    b.Property<string>("Name");

                    b.Property<int>("Sort");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UwlButtons");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("APIAddress");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<string>("Icon");

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("Memo");

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<string>("ParentIdArr");

                    b.Property<int>("Sort");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.Property<string>("UrlAddress");

                    b.HasKey("Id");

                    b.ToTable("UwlMenus");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysMenuButton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("APIAddress");

                    b.Property<Guid>("ButtonId");

                    b.Property<string>("ButtonStyle");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("KeyCode");

                    b.Property<Guid>("MenuId");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UwlMenuButtons");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysOrganize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<int>("Depth");

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("Name");

                    b.Property<Guid>("ParentId");

                    b.Property<int>("Sort");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UwlSysOrganizes");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("Memo");

                    b.Property<string>("Name");

                    b.Property<int>("RoletState");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UwlRoles");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysRoleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("Memo");

                    b.Property<string>("Name");

                    b.Property<string>("RoleIds");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UwlRoleGroups");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysRoleRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ButtonIds");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDrop");

                    b.Property<Guid>("MenuId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UwlRoleRights");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<int>("AccountState");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<Guid>("DepartmentId");

                    b.Property<string>("Email");

                    b.Property<int>("EmpliyeeType");

                    b.Property<DateTime?>("EntryDate");

                    b.Property<bool?>("IsDrop");

                    b.Property<string>("JobName");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<Guid>("OrganizeId");

                    b.Property<string>("Password");

                    b.Property<string>("QQ");

                    b.Property<bool>("Sex");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.Property<string>("WeChat");

                    b.HasKey("Id");

                    b.ToTable("UwlUsers");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("CreatedId");

                    b.Property<string>("CreatedName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsDrop");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime?>("UpdateDate");

                    b.Property<Guid?>("UpdateId");

                    b.Property<string>("UpdateName")
                        .HasMaxLength(50);

                    b.Property<Guid>("UserIdOrDepId");

                    b.HasKey("Id");

                    b.ToTable("UwlUserRoles");
                });

            modelBuilder.Entity("Uwl.Data.Model.BaseModel.SysUsersOrganizeRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsMain");

                    b.Property<Guid>("OrgId");

                    b.Property<int>("Sort");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UwlUsersOrganizeRelation");
                });
#pragma warning restore 612, 618
        }
    }
}
